INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:44:53] "[31m[1mGET / HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:44:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:45:04] "[31m[1mGET / HTTP/1.1[0m" 405 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:45:39] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:45:39] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:45:39] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:54:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:54:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:54:52] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:25] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:25] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:26] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:27] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:55:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:58] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:59] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:58:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:59:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:59:01] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 13:59:01] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:38] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:39] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:39] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:01:39] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:11] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:12] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:12] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:13] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:13] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:42] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:02:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:15:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:15:13] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:15:13] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:application:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 10, in homepage
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\user\Desktop\Diabetes_prediction\templates\index.html", line 59, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:17:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:application:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 10, in homepage
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\user\Desktop\Diabetes_prediction\templates\index.html", line 59, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:17:31] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:application:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 10, in homepage
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\user\Desktop\Diabetes_prediction\templates\index.html", line 59, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:17:50] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:application:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 10, in homepage
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\user\anaconda3\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\user\Desktop\Diabetes_prediction\templates\index.html", line 59, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:17:51] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:18:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:18:48] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:18:48] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:19:37] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:19:37] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:19:37] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:44] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:44] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:45] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:46:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got all data..
INFO:root:got all data..
INFO:root:got all data..
INFO:root:got all data..
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:47:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:47:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:47:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:47:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:47:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:51:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:53:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:53:01] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:53:01] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:53:12] "[31m[1mGET /predict HTTP/1.1[0m" 405 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:application:Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\Lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'predictDiabetes' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 14:54:00] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:06:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:06:56] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:06:56] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:06:56] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:root:got all data..
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:12:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\Desktop\Diabetes_prediction\application.py", line 17, in predictDiabetes
    df = pd.DataFrame(names = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])
TypeError: __init__() got an unexpected keyword argument 'names'
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:13:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\Desktop\Diabetes_prediction\application.py", line 17, in predictDiabetes
    df = pd.DataFrame(names = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])
TypeError: __init__() got an unexpected keyword argument 'names'
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
INFO:root:got all data..
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:18:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:18:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\Desktop\Diabetes_prediction\application.py", line 32, in predictDiabetes
    pred = model.predict(df)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:/Users/user/Desktop/Diabetes_prediction/application.py", line 33, in predictDiabetes
    pred = model.predict(df)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 419, in predict
    scores = self.decision_function(X)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by LogisticRegression.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:20:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:application:Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:/Users/user/Desktop/Diabetes_prediction/application.py", line 26, in predictDiabetes
    df = pd.DataFrame({'Pregnancies':Pregnancies,'Glucose':Glucose,'BloodPressure':BloodPressure,'SkinThickness':SkinThickness,'Insulin':Insulin,'BMI':BMI,'DiabetesPedigreeFunction':DiabetesPedigreeFunction,'Age':Age})
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\pandas\core\frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\pandas\core\internals\construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\pandas\core\internals\construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\pandas\core\internals\construction.py", line 645, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:24:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
INFO:root:got predictions!!
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:27:06] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:27:06] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:27:06] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:application:Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\user\anaconda3\envs\practice\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'predictDiabetes' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:31:40] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:31:57] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:31:57] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:31:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:34:28] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:34:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:35:38] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:35:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:18] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:18] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:45] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:45] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:36:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:38:06] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:38:06] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:38:06] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:15] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:15] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Oops, you have Diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:43] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:43] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:43:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:root:got all data..
INFO:root:got predictions!!
INFO:root:prediction is Congratulations!! you don't have diabetes
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:44:42] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:44:42] "[33mGET /style.css HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Jan/2024 20:44:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
